color_theme = "hacker"
theme_background = false
vim_keys = true
rounded_corners = true
graph_symbol = "braille"
shown_boxes = "cpu mem net proc"
update_ms = 1000
proc_sorting = "cpu lazy"
proc_tree = false
proc_gradient = true
cpu_graph_upper = "total"
cpu_graph_lower = "total"
show_uptime = true
